admin_lte:
    options:
        default_avatar: 'bundles/adminlte/images/default_avatar.png'
        skin: 'skin-blue'
        fixed_layout: false
        boxed_layout: false
        collapsed_sidebar: false
        mini_sidebar: false
        form_theme: default
        max_navbar_notifications: 5
        max_navbar_tasks: 5
        max_navbar_messages: 5

    theme:
        widget:
            type: 'primary'
            bordered: true
            collapsible: false
            collapsible_title: 'Collapse'
            removable: false
            removable_title: 'Remove'
            solid: false
            use_footer: true
        button:
            type: 'primary'
            size: false

    knp_menu:
        enable: true
        main_menu: 'adminlte_main'
        breadcrumb_menu: false

    routes:
        adminlte_welcome: 'app_modules_main_ui_dashboard_admin'
        adminlte_login: 'fos_user_security_login '
        adminlte_login_check: 'fos_user_security_check'
        adminlte_message: 'message'
        adminlte_messages: 'messages'
        adminlte_notification: 'notification'
        adminlte_notifications: 'notifications'
        adminlte_task: 'task'
        adminlte_tasks: 'tasks'
        adminlte_profile: 'app_modules_user_ui_admin_account_account'