doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Lib/Infrastructure/Doctrine/Migrations'
      # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: App\Lib\Infrastructure\Doctrine\Migrations
