doctrine:
  dbal:
    types:
      AttachmentFileCategoryEnum: App\Modules\Attachment\Domain\File\Enum\CategoryEnum
      UserUserAvatarEnum: App\Modules\User\Domain\User\Enum\TypeAvatarEnum
  orm:
    entity_managers:
      default:
        mappings:
          gedmo_loggable:
            type: annotation
            prefix: Gedmo\Loggable\Entity
            dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            alias: GedmoLoggable
            is_bundle: false
          libDomain:
            type: annotation
            dir: '%kernel.project_dir%/src/Lib/Domain'
            prefix: App\Lib\Domain
          ProductDomain:
            type: annotation
            dir: '%kernel.project_dir%/src/Modules/Product/Domain'
            prefix: App\Modules\Product\Domain
          UserDomain:
            type: annotation
            dir: '%kernel.project_dir%/src/Modules/User/Domain'
            prefix: App\Modules\User\Domain
          AttachmentDomain:
            type: annotation
            dir: '%kernel.project_dir%/src/Modules/Attachment/Domain'
            prefix: App\Modules\Attachment\Domain