security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        App\Modules\User\Domain\User\Entity\UserEntity: plaintext

    role_hierarchy:
        ROLE_ADMIN: [ROLE_CLIENT, ROLE_PARTNER, ROLE_SELLER]

        ROLE_USER: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ALLOWED_TO_SWITCH, ROLE_ADMIN]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            switch_user: true
            provider: chain_provider
            form_login:
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /dashboard
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /
                invalidate_session: false
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
