parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude:
            - '../src/Modules/*/Domain/*/Entity'
            - '../src/Kernel.php'
        public: true

    App\Lib\Infrastructure\Doctrine\Fixtures\:
        resource: '../src/Lib/Infrastructure/Doctrine/Fixtures'
        tags: ['doctrine.fixture.orm']